### PR TITLE
styles: create base style for Booking component

### LINKED ISSUE #4: Booking Screen Style
# REQUIREMENTS
Create base style for Booking Screen

# DESIGN

### PR DESCRIPTION
**Pull request by Ch4s3d**
Co-Authored-By: Carlos De Santis <95086934+Charly77955@users.noreply.github.com>
Co-Authored-By: Valeria Aguirre <102261096+aguirre-valeria@users.noreply.github.com>

# Description
- Add styles for the Booking Screen  
 
 Examples:
 - 
 
 # Testing
 -
 
 Example:
 - 
  
  ## Screenshots 
Captura de pantalla 2022-08-31 175353

### CODE REVIEW

**Review by Charly77955 — APPROVED** [review]
All ok

**Comment by aguirre-valeria** [comment]
All is ok

**Review by aguirre-valeria — APPROVED** [review]
All is ok

**Review by Charly77955 — APPROVED** [review]
all ok

**Pull request merged**
